### ISSUE TITLE
Error: Calls from old Quanteda Version

### ISSUE THREAD

**Issue by msaeltzer** [kbenoit/wordshoal#13]
Main functions doesn't work because wordfish is not part of main quanteda since 2.0.
Fix: changing requirements and changing quanteda::textmodel_wordfish to quanteda.textmodels::textmodel_wordfish. Maybe integrate in quanteda.textmodels instead?
best regards Marius

**Comment by kbenoit** [comment]
We split the `textmodel_wordshoal()` because it needed maintenance that @lauderdale was unwilling to provide, so unless that happens, it's unlikely to make its way into **quanteda.textmodels**, but I can fix the dependency caused by changes in **quanteda** v2.

**Comment by kbenoit** [comment]
Solved in e93ebbf
